[ENTITIES.player]
player = true
position2 = true
drawable = true

[ENTITIES.player.velocity2]
x = 0.0
y = 0.0

[ENTITIES.player.sprite]
path = "assets/images/player.png"
size = [80, 80]
scale = [160, 160]
origin = [40, 80]
layer = 2

[ENTITIES.player.animation]
frames = [
    [[0, 0], 8, 0.09, true],
    [[0, 1], 8, 0.09, true],
    [[0, 2], 8, 0.09, true],
    [[0, 3], 4, 0.2, true],
    [[0, 4], 4, 0.2, true],
    [[0, 5], 4, 0.2, true],
]
